title: Bedraad meerdere enkele LED's
hero_image: images/banner.png
description: Een demonstratie van hoe je meerdere LED's kunt aansluiten op een Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - 
    title: Bedraad meerdere enkele LED's
