title: Câbler plusieurs LED simples
hero_image: images/banner.png
description: Une démonstration de la façon de câbler plusieurs LED simples à un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-08"
steps:
  - 
    title: Câbler plusieurs LED simples
